#!/bin/sh
#
# Perform necessary universal-package setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ `uname -m` == 'x86_64' ]
then
  installer -pkg /tmp/chef-pkgs/chef-18.0.92-1.x86_64.pkg -target LocalSystem -verbose
elif [ `uname -m` == 'arm64' ]
then
  installer -pkg /tmp/chef-pkgs/chef-18.0.92-1.arm64.pkg -target LocalSystem -verbose
fi

echo "Thank you for installing universal-package!"

exit 0
