# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef-universal

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-infra-notify

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true

pipelines:
  - omnibus/release:
      definition: .expeditor/release.omnibus.yml
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

subscriptions:
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_artifactory_artifact